name: binaryninja-nightly
run-name: binaryninja-nightly

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Daily

jobs:
  binaryninja-nightly-dev-release:
    uses: ./.github/workflows/binaryninja-release.yml
    with:
      release_tag: "binaryninja-dev"
      release_title: "dev"
      release_notes: >
        "Binary Ninja does frequent releases on their dev branch. For
        the binexport plugin to work with the latest API, the plugin is built
        once a day."
      version: "dev"