name: binaryninja-dev
run-name: binaryninja-dev

on:
  workflow_dispatch:
    inputs:
      build:
        type: choice
        description: Build All or Last 24 Hours
        options:
        - All
        - Last 24 hours
        default: 'Last 24 hours'
  schedule:
    - cron: '0 0 * * *' # Daily

jobs:
  get-dev-tag-list:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-dev-tags.outputs.matrix }}
    steps:
    - name: Get Dev Tags
      id: get-dev-tags
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        dev_tags=""

        # calculating twenty four hours ago
        current_timestamp=$(date +"%s")
        twenty_four_hours_ago=$((current_timestamp - 24 * 60 * 60))

        # getting the latest plugin release with a list of assets
        if [[ "${{ inputs.build }}" == "All"]]; then
          latest_plugin_release=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/releases/latest)
        fi

        tags=$(gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/Vector35/binaryninja-api/git/refs/tags)
        while read -r ref_name tag_hash tag_type; do
          if [[ "$tag_type" == "commit" ]]; then
            tag_name="${ref_name#refs/tags/}"
            if [[ "$tag_name" == "dev/"* ]]; then
              tag_json=$(gh api \
                -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                /repos/Vector35/binaryninja-api/git/commits/$tag_hash)

              # determining if the tag was 24 hours ago
              tag_date=$(echo $tag_json | jq -r .committer.date)
              date_timestamp=$(date -d $tag_date +"%s")

              # adding the tag to the list if it is within 24 hours
              if [[ $date_timestamp -gt $twenty_four_hours_ago ]]; then
                dev_tags+="{\"tag_name\": \"$tag_name\", \"tag_date\": \"$tag_date\"},"
              # if building all the tags
              elif [[ "${{ inputs.build }}" == "All"]]; then
                number_of_assets_found=$(echo $latest_plugin_release | jq '[.assets.[] | \
                  select(.name | contains("$tag_name"))] | length')

                # only build tags that don't exist
                if [[ $number_of_assets_found == 0 ]]; then
                  dev_tags+="{\"tag_name\": \"$tag_name\", \"tag_date\": \"$tag_date\"},"
                fi
              fi
            fi
          fi
        done < <(echo $tags | jq -r '.[] | "\(.ref) \(.object.sha) \(.object.type)"')

        # removing last comma
        dev_tags="${dev_tags%,}"

        dev_tags="{\"include\": [$dev_tags]}"
        echo "matrix=$dev_tags"
        echo "matrix=$dev_tags" >> $GITHUB_OUTPUT

  #binaryninja-nightly-dev-release:
  #  needs: get-dev-tag-list
  #  strategy:
  #    fail-fast: false
  #    matrix: ${{ fromJSON(needs.get-dev-tag-list.outputs.matrix) }}
  #  uses: ./.github/workflows/build-release.yml
  #  with:
  #    binaryninja_version: ${{ matrix.tag_name }}