name: binaryninja-stable
run-name: binaryninja-stable ${{ inputs.binaryninja-version }}

on:
  workflow_dispatch:
    inputs:
      binaryninja-version:
        description: "Binary Ninja API Tag or Commit for Specific Version of the API"
        required: true
        type: string
  schedule:
    - cron: '0 1 * * *' # Daily

jobs:
  get-plugin-version:
    runs-on: ubuntu-latest
    outputs:
      plugin_version: ${{ steps.get-local-plugin-version.outputs.plugin_version }}
    steps:
    - name: Get the Version Number of this Plugin
      id: get-local-plugin-version
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        cat VERSION_PLUGIN.txt >> $GITHUB_OUTPUT
        cat VERSION_PLUGIN.txt | awk '{print "BinExport Plugin Version: "$1}'



  check-for-release:
    if: inputs.binaryninja-version == ''
    runs-on: ubuntu-latest
    outputs:
      build_within_24_hours: ${{ steps.is-build-within-24-hours.outputs.build_within_24_hours }}
      latest_commit_date: ${{ steps.get-latest-tag-info.outputs.latest_tag_commit_date}}
      latest_tag_hash: ${{ steps.get-latest-tag-hash.outputs.latest_tag_hash }}
      latest_tag_name: ${{ steps.get-latest-tag-info.outputs.latest_tag_name }}

    steps:
    - name: Get Latest Tag Hash from Binary Ninja API
      id: get-latest-tag-hash
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        tag_hash=$(gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/Vector35/binaryninja-api/git/refs/tags \
          | jq -r .[-1].object.sha)
        echo "latest_tag_hash=$tag_hash"
        echo "latest_tag_hash=$tag_hash" >> $GITHUB_OUTPUT

    - name: Get Tag Info
      id: get-latest-tag-info
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        latest_tag=$(gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/Vector35/binaryninja-api/git/tags/${{ steps.get-latest-tag-hash.outputs.latest_tag_hash }})
        commit_date=$(echo $latest_tag | jq -r .tagger.date)
        echo "latest_tag_commit_date=$commit_date"
        echo "latest_tag_commit_date=$commit_date" >> $GITHUB_OUTPUT
        tag_name=$(echo $latest_tag | jq -r .tag)
        echo "latest_tag_name=$tag_name"
        echo "latest_tag_name=$tag_name" >> $GITHUB_OUTPUT

    - name: Is Build Within 24 Hours?
      id: is-build-within-24-hours
      run: |
        date_timestamp=$(date -d ${{ steps.get-latest-tag-info.outputs.latest_tag_commit_date }} +"%s")
        current_timestamp=$(date +"%s")
        twenty_four_hours_ago=$((current_timestamp - 24 * 60 * 60))

        if [[ $date_timestamp -gt $twenty_four_hours_ago ]]; then
          echo "build_within_24_hours=true"
          echo "build_within_24_hours=true" >> $GITHUB_OUTPUT
        else
          echo "build_within_24_hours=false"
          echo "build_within_24_hours=false" >> $GITHUB_OUTPUT
        fi

  binaryninja-stable-release-last-24:
    uses: ./.github/workflows/binaryninja-release.yml
    needs: [check-for-release, get-plugin-version]
    if: needs.check-for-release.outputs.build_within_24_hours == 'true'
    with:
      binaryninja-version: "${{ needs.check-for-release.outputs.latest_tag_name }}"
      plugin-version: "${{ needs.get-plugin-version.outputs.plugin_version }}"
      release_tag: "${{ needs.check-for-release.outputs.latest_tag_name }}"
      release_title: "BinExport Binary Ninja Plugin Latest Stable Build (${{ needs.check-for-release.outputs.latest_tag_name }})"
      release_notes: >
        "This is a build of BinExport plugin for Binary Ninja from the latest
        stable Binary Ninja API ${{ needs.check-for-release.outputs.latest_tag_name }}."

  binaryninja-stable-release:
    uses: ./.github/workflows/binaryninja-release.yml
    needs: get-plugin-version
    if: github.event.inputs.binaryninja-version != ''
    with:
      binaryninja-version: "${{ github.event.inputs.binaryninja-version }}"
      plugin-version: "${{ needs.get-plugin-version.outputs.plugin_version }}"
      release_tag: "${{ needs.get-plugin-version.outputs.plugin_version }}"
      release_title: "${{ needs.get-plugin-version.outputs.plugin_version }}"
      release_notes: >
        "This is a build of BinExport plugin for Binary Ninja from the ${{ github.event.inputs.binaryninja-version }}
        stable Binary Ninja API."