name: binaryninja-dev
run-name: binaryninja-dev

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Daily

jobs:
  binaryninja-nightly-dev-release:
    uses: ./.github/workflows/binaryninja-release.yml
    with:
      binaryninja_version: "dev"
      release_title: "BinExport Binary Ninja Plugin"
      release_notes: >
        "This is a build of the BinExport plugin for Binary Ninja from the following versions:"