name: build-specific-versions
run-name: build-specific-versions ${{ inputs.plugin_version }} ${{ inputs.binaryninja_version }} ${{ inputs.binexport_version }}

on:
  workflow_dispatch:
    inputs:
      binaryninja_version:
        description: "Binary Ninja API Tag or Commit for Specific Version of the API"
        type: string
      binexport_version:
        description: "BinExport Tag or Commit for Specific Version of the Library from Google"
        type: string
      plugin_version:
        description: "Plugin Tag or Commit for Specific Version Number of this Plugin"
        type: string
  schedule:
    - cron: '0 1 * * *' # Daily

jobs:
  check-for-release:
    if: inputs.binaryninja_version == ''
    runs-on: ubuntu-latest
    outputs:
      release_within_24_hours: ${{ steps.is-tag-within-24-hours.outputs.release_within_24_hours }}
      binaryninja_version: ${{ steps.get-binaryninja-version.outputs.binaryninja_version }}

    steps:
    - name: Get Latest Tag Info from Binary Ninja API
      if: inputs.binaryninja_version == ''
      id: get-latest-binaryninja-tag-info
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        tags=$(gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/Vector35/binaryninja-api/git/refs/tags)
        tag_hash=$(echo $tags | jq -r .[-1].object.sha)
        tag_type=$(echo $tags | jq -r .[-1].object.type)
        tag_ref=$(echo $tags | jq -r .[-1].ref)
        echo "latest_binaryninja_tag_hash=$tag_hash"
        echo "latest_binaryninja_tag_hash=$tag_hash" >> $GITHUB_OUTPUT
        echo "latest_binaryninja_tag_type=$tag_type"
        echo "latest_binaryninja_tag_type=$tag_type" >> $GITHUB_OUTPUT

        # easier to get the tag name by parsing ref
        # difference between lightweight tag and annotated tag
        # doesn't provide a good way of getting the tag name through the API
        tag_name="${tag_ref##*/}"
        echo "latest_binaryninja_tag_name=$tag_name"
        echo "latest_binaryninja_tag_name=$tag_name" >> $GITHUB_OUTPUT

        # git/tags api only works for annotated tag objects
        # lightweight tags have to be referenced by commit
        if [[ "$tag_type" == "tag" ]]; then
          commit_date=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/Vector35/binaryninja-api/git/tags/$tag_hash | \
            jq -r .tagger.date)
        elif [[ "$tag_type" == "commit" ]]; then
          commit_date=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/Vector35/binaryninja-api/git/commits/$tag_hash | \
            jq -r .committer.date)
        else
          commit_date=""
        fi
        echo "latest_tag_commit_date=$commit_date"
        echo "latest_tag_commit_date=$commit_date" >> $GITHUB_OUTPUT

    - name: Get Binary Ninja API Version
      id: get-binaryninja-version
      run: |
        # checking if the binary ninja api version is blank
        # if it is, use the latest version
        if [[ -z "${{ inputs.binaryninja_version }}" ]]; then
          echo "binaryninja_version=${{ steps.get-latest-binaryninja-tag-info.outputs.latest_binaryninja_tag_name }}"
          echo "binaryninja_version=${{ steps.get-latest-binaryninja-tag-info.outputs.latest_binaryninja_tag_name }}" >> $GITHUB_OUTPUT
        else
          echo "binaryninja_version=${{ inputs.binaryninja_version }}"
          echo "binaryninja_version=${{ inputs.binaryninja_version }}" >> $GITHUB_OUTPUT
        fi

    - name: Is Tag Within 24 Hours?
      if: github.event_name == 'schedule'
      id: is-tag-within-24-hours
      run: |
        date_timestamp=$(date -d ${{ steps.get-latest-binaryninja-tag-info.outputs.latest_tag_commit_date }} +"%s")
        current_timestamp=$(date +"%s")
        twenty_four_hours_ago=$((current_timestamp - 24 * 60 * 60))

        if [[ $date_timestamp -gt $twenty_four_hours_ago ]]; then
          echo "release_within_24_hours=true"
          echo "release_within_24_hours=true" >> $GITHUB_OUTPUT
        else
          echo "release_within_24_hours=false"
          echo "release_within_24_hours=false" >> $GITHUB_OUTPUT
        fi

  binaryninja-stable-release-last-24:
    uses: ./.github/workflows/build-release.yml
    needs: check-for-release
    if: (needs.check-for-release.outputs.release_within_24_hours == 'true') && (github.event_name == 'schedule')
    with:
      binaryninja_version: ${{ needs.check-for-release.outputs.binaryninja_version }}
      binexport_version: ${{ inputs.binexport_version }}
      plugin_version: ${{ inputs.plugin_version }}

  binaryninja-stable-release:
    uses: ./.github/workflows/build-release.yml
    needs: check-for-release
    if: github.event_name != 'schedule'
    with:
      binaryninja_version: ${{ needs.check-for-release.outputs.binaryninja_version }}
      binexport_version: ${{ inputs.binexport_version }}
      plugin_version: ${{ inputs.plugin_version }}