name: cmake-reusable

env:
  BUILD_DIR: build

on:
  workflow_dispatch:
    inputs:
      base_artifact_filename:
        description: >
          "The base filename of the artifact .zip that is created OS and
          architecture are appended"
        required: False
        default: "BinExport"
        type: string
      binaryninja_version:
        description: "Binary Ninja API Tag or Commit for Specific Version of the API"
        required: False
        default: "dev"
        type: string
      binexport_version:
        description: "BinExport Tag or Commit for Specific Version of the Library from Google"
        required: False
        default: "main"
        type: string
      build_type:
        description: "Debug or Release builds"
        required: false
        default: "Release"
        type: string
      os:
        description: "Operating System to Build On"
        required: true
        type: string
      patch_file:
        description: "Workflow Patch File for Older Versions of Binary Ninja"
        required: False
        default: ""
        type: string
      plugin_version:
        description: "Version Number for this Plugin"
        required: false
        type: string

  workflow_call:
    inputs:
      base_artifact_filename:
        description: >
          "The base filename of the artifact .zip that is created OS and
          architecture are appended"
        required: False
        default: "BinExport"
        type: string
      binaryninja_version:
        description: "Binary Ninja API Tag or Commit for Specific Version of the API"
        required: False
        default: "dev"
        type: string
      binexport_version:
        description: "BinExport Tag or Commit for Specific Version of the Library from Google"
        required: False
        default: "main"
        type: string
      build_type:
        description: "Debug or Release builds"
        required: false
        default: "Release"
        type: string
      os:
        description: "Operating System to Build On"
        required: true
        type: string
      patch_file:
        description: "Workflow Patch File for Older Versions of Binary Ninja"
        required: False
        default: ""
        type: string
      plugin_version:
        description: "Version Number for this Plugin"
        required: false
        type: string
    outputs:
      plugin_version:
        description: "The Version of This Plugin in String Format (can change depending on commit)"
        value: ${{ jobs.build.outputs.plugin_version }}

jobs:
  build:
    name: Build ${{ inputs.os }}
    runs-on: ${{ inputs.os }}
    outputs:
      plugin_version: ${{ steps.get-plugin-version.outputs.plugin_version }}

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4

    - name: Switch to Specific Plugin Version
      if: inputs.plugin_version
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        git fetch --tags
        git checkout --force ${{ inputs.plugin_version }}
        git submodule update --init --recursive

        # Attempt to get the tag name
        TAG=$(git describe --exact-match --tags 2>/dev/null)

        # Check if a tag was found
        if [ -n "$TAG" ]; then
          echo "$TAG" > VERSION_PLUGIN.txt
        else
          # If no tag, get the current branch name
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "$BRANCH" > ${{ github.workspace }}/VERSION_PLUGIN.txt
        fi

    - name: Update submodules
      shell: bash
      working-directory: ${{ github.workspace }}
      run: git submodule update --init --recursive

    - name: Get the Version Number of this Plugin
      id: get-plugin-version
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        cat VERSION_PLUGIN.txt | awk '{print "BinExport Plugin Version: "$1}'
        cat VERSION_PLUGIN.txt | awk '{print "plugin_version="$1}' >> $GITHUB_OUTPUT

    - name: Update Binexport Library Version File
      id: get-binexport-version
      shell: bash
      working-directory: ${{ github.workspace }}/third-party/binexport/src
      run: |
        # Putting in format of major version - date (12-20250619)
        cat CMakeLists.txt | grep "project(binexport VERSION" | \
          awk -F " " '{print $3}' | awk -F ")" '{print $1}' | tr -d '\n' > ../../../VERSION_BINEXPORT_LIB.txt
        git log -1 --pretty=format:%ad --date=format:"-%Y%m%d" >> ../../../VERSION_BINEXPORT_LIB.txt
        cat ../../../VERSION_BINEXPORT_LIB.txt | awk '{print "BinExport Lib Version: "$1}'
        cat ../../../VERSION_BINEXPORT_LIB.txt | awk '{print "binexport_version="$1}' >> $GITHUB_OUTPUT

    - name: Get Specific Binary Ninja API Version
      id: get-binaryninja-version
      shell: bash
      working-directory: ${{ github.workspace }}/third-party/binaryninja-api
      run: |
        git fetch --tags
        git checkout --force ${{ inputs.binaryninja_version }}
        git submodule update --init --recursive

        # Attempt to get the tag name
        TAG=$(git describe --exact-match --tags 2>/dev/null)

        # Check if a tag was found
        if [ -n "$TAG" ]; then
          echo "$TAG" > VERSION_BINARYNINJA_LIB.txt
        else
          # If no tag, get the current branch name
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "$BRANCH" > ${{ github.workspace }}/VERSION_BINARYNINJA_LIB.txt
        fi

        cat VERSION_BINARYNINJA_LIB.txt | awk '{print "BinaryNinja API Lib Version: "$1}'
        cat VERSION_BINARYNINJA_LIB.txt | awk '{print "binaryninja_version="$1}' >> $GITHUB_OUTPUT

    - name: Patch api to allow building headlessly
      if: inputs.patch_file
      shell: bash
      working-directory: ${{ github.workspace }}/third-party/binaryninja-api
      run: |
        git apply --verbose ${{ inputs.patch_file }}

    - name: Enable Developer Command Prompt (Windows)
      if: inputs.os == 'windows-latest'
      uses: ilammy/msvc-dev-cmd@v1.13.0

    - name: Enable mold linker (Linux)
      if: inputs.os == 'ubuntu-latest'
      uses: rui314/setup-mold@v1

    - name: Setup CMake and Ninja
      uses: lukka/get-cmake@v4.0.2
      with:
        cmakeVersion: 4.0.2
        ninjaVersion: 1.12.1

    - name: Cache Restore CMake Build
      id: cache-restore-build
      uses: actions/cache/restore@v4
      with:
        path: build
        key: ${{ runner.os }}-${{ runner.arch }}-${{ steps.get-binaryninja-version.outputs.binaryninja_version }}-${{ steps.get-binexport-version.outputs.binexport_version }}-cmake-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

    - name: Configure CMake
      id: configure-cmake
      shell: bash
      run: |
        cmake -S "${{ github.workspace }}" -G Ninja -B build \
          "-DCMAKE_BUILD_TYPE=${{ inputs.build_type }}"

    - name: Build
      shell: bash
      run: cmake --build ${{ env.BUILD_DIR }}

    - name: Cache Save CMake Build
      id: cache-save-build
      uses: actions/cache/save@v4
      with:
        path: build
        key: ${{ runner.os }}-${{ runner.arch }}-${{ steps.get-binaryninja-version.outputs.binaryninja_version }}-${{ steps.get-binexport-version.outputs.binexport_version }}-cmake-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

    - name: Upload Build Artifacts
      id: upload-build-artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.base_artifact_filename }}${{ steps.get-binexport-version.outputs.binexport_version }}_BinaryNinja-${{ steps.get-binaryninja-version.outputs.binaryninja_version }}_Plugin-${{ steps.get-plugin-version.outputs.plugin_version }}_${{ runner.os }}-${{ runner.arch }}
        path: |
          ${{ github.workspace }}/${{ env.BUILD_DIR }}/*.dll
          ${{ github.workspace }}/${{ env.BUILD_DIR }}/*.dylib
          ${{ github.workspace }}/${{ env.BUILD_DIR }}/*.so