name: cmake-reusable
run-name: cmake-reusable

env:
  BUILD_DIR: build

on: 
  workflow_dispatch:
    inputs:
      base_artifact_filename:
        description: >
          "The base filename of the artifact .zip that is created OS and
          architecture are appended"
        required: false
        default: "Binexport"
        type: string
      build_type:
        description: "Debug or Release builds"
        required: false
        default: "Release"
        type: string

  workflow_call:
    inputs:
      base_artifact_filename:
        description: >
          "The base filename of the artifact .zip that is created OS and
          architecture are appended"
        required: false
        default: "Binexport"
        type: string
      build_type:
        description: "Debug or Release builds"
        required: false
        default: "Release"
        type: string

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, macos-latest, windows-latest]
        version: # BinaryNinja API Versions
        - name: dev
        - name: v5.0.7486-stable
        - name: v5.0.7290-stable
        - name: v4.2.6455-stable
        - name: v4.1.5902-stable
          patch-file: ../../.github/workflows/4.1_0001-Support-building-plugins-without-an-install.patch
        - name: v4.1.5747-stable
          patch-file: ../../.github/workflows/4.1_0001-Support-building-plugins-without-an-install.patch
        - name: v4.0.5336-stable
          patch-file: ../../.github/workflows/4.0_0001-Support-building-plugins-without-an-install.patch
        - name: v4.0.4958-stable
          patch-file: ../../.github/workflows/4.0_0001-Support-building-plugins-without-an-install.patch
        - name: v4.0.4911-stable
          patch-file: ../../.github/workflows/4.0_0001-Support-building-plugins-without-an-install.patch
        - name: v3.5.4526-stable
          patch-file: ../../.github/workflows/3.5_0001-Support-building-plugins-without-an-install.patch
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4

    - name: Update submodules 
      shell: bash
      working-directory: ${{ github.workspace }}
      run: git submodule update --init --recursive

    - name: Get Specific Binary Ninja API Version 
      shell: bash
      working-directory: ${{ github.workspace }}/third-party/binaryninja-api
      run: |
        git fetch --tags
        git checkout --force ${{ matrix.version.name }}
        git submodule update --init --recursive

    - name: Patch api to allow building headlessly
      if: matrix.version.patch-file
      shell: bash
      working-directory: ${{ github.workspace }}/third-party/binaryninja-api
      run: |
        git apply --verbose ${{ matrix.version.patch-file }}

    - name: Enable Developer Command Prompt (Windows)
      if: matrix.os == 'windows-latest'
      uses: ilammy/msvc-dev-cmd@v1.13.0

    - name: Enable mold linker (Linux)
      if: matrix.os == 'ubuntu-latest'
      uses: rui314/setup-mold@v1

    - name: Setup CMake and Ninja
      uses: lukka/get-cmake@v4.0.2
      with:
        cmakeVersion: 4.0.2
        ninjaVersion: 1.12.1

    - name: Configure CMake
      shell: bash
      run: |
        cmake -S "${{ github.workspace }}" -G Ninja -B build \
          "-DCMAKE_BUILD_TYPE=${{ inputs.build_type }}"

    - name: Build
      shell: bash
      run: cmake --build ${{ env.BUILD_DIR }}

    - name: Upload Build Artifacts
      id: upload-build-artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.base_artifact_filename }}-${{ runner.os }}-${{ runner.arch }}-${{ matrix.version.name }}
        path: |
          ${{ github.workspace }}/${{ env.BUILD_DIR }}/*.dll
          ${{ github.workspace }}/${{ env.BUILD_DIR }}/*.dylib
          ${{ github.workspace }}/${{ env.BUILD_DIR }}/*.so