name: cmake-reusable

env:
  BUILD_DIR: build

on:
  workflow_dispatch:
    inputs:
      base_artifact_filename:
        description: >
          "The base filename of the artifact .zip that is created OS and
          architecture are appended"
        required: false
        default: "BinExport-BinaryNinja"
        type: string
      build_type:
        description: "Debug or Release builds"
        required: false
        default: "Release"
        type: string
      os:
        description: "Operating System to Build On"
        required: true
        type: string
      patch-file:
        description: "Workflow Patch File for Older Versions of Binary Ninja"
        required: False
        default: ""
        type: string
      version:
        description: "Binary Ninja API Tag or Commit"
        required: true
        default: "dev"
        type: string

  workflow_call:
    inputs:
      base_artifact_filename:
        description: >
          "The base filename of the artifact .zip that is created OS and
          architecture are appended"
        required: false
        default: "BinExport"
        type: string
      build_type:
        description: "Debug or Release builds"
        required: false
        default: "Release"
        type: string
      os:
        description: "Operating System to Build On"
        required: true
        type: string
      patch-file:
        description: "Workflow Patch File for Older Versions of Binary Ninja"
        required: False
        default: ""
        type: string
      version:
        description: "Binary Ninja API Tag or Commit"
        required: true
        default: "dev"
        type: string

jobs:
  build:
    runs-on: ${{ inputs.os }}

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4

    - name: Update submodules
      shell: bash
      working-directory: ${{ github.workspace }}
      run: git submodule update --init --recursive

    - name: Get Specific Binary Ninja API Version
      shell: bash
      working-directory: ${{ github.workspace }}/third-party/binaryninja-api
      run: |
        git fetch --tags
        git checkout --force ${{ inputs.version }}
        git submodule update --init --recursive

    - name: Patch api to allow building headlessly
      if: inputs.patch-file
      shell: bash
      working-directory: ${{ github.workspace }}/third-party/binaryninja-api
      run: |
        git apply --verbose ${{ inputs.patch-file }}

    - name: Enable Developer Command Prompt (Windows)
      if: inputs.os == 'windows-latest'
      uses: ilammy/msvc-dev-cmd@v1.13.0

    - name: Enable mold linker (Linux)
      if: inputs.os == 'ubuntu-latest'
      uses: rui314/setup-mold@v1

    - name: Setup CMake and Ninja
      uses: lukka/get-cmake@v4.0.2
      with:
        cmakeVersion: 4.0.2
        ninjaVersion: 1.12.1

    - name: Configure CMake
      id: configure-cmake
      shell: bash
      run: |
        cmake -S "${{ github.workspace }}" -G Ninja -B build \
          "-DCMAKE_BUILD_TYPE=${{ inputs.build_type }}"
        echo "BINEXPORT_VERSION=$BINEXPORT_VERSION" >> $GITHUB_OUTPUT

    - name: Build
      shell: bash
      run: cmake --build ${{ env.BUILD_DIR }}

    - name: Upload Build Artifacts
      id: upload-build-artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.base_artifact_filename }}${{ steps.configure-cmake.outputs.BINEXPORT_VERSION }}-${{ runner.os }}-${{ runner.arch }}-${{ inputs.version }}
        path: |
          ${{ github.workspace }}/${{ env.BUILD_DIR }}/*.dll
          ${{ github.workspace }}/${{ env.BUILD_DIR }}/*.dylib
          ${{ github.workspace }}/${{ env.BUILD_DIR }}/*.so